[versions]
kotlin = "1.9.0"
ktor = "1.6.7"
jackson = "2.11.2"

[libraries]
compose-material-icons = "org.jetbrains.compose.material:material-icons-extended-desktop:1.3.1"

ktor-server = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-websockets = { module = "io.ktor:ktor-websockets", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-auth = { module = "io.ktor:ktor-auth", version.ref = "ktor" }

kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0"
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0-RC.2"

logback = "ch.qos.logback:logback-classic:1.4.7"

jackson-module = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-dataformat = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }

jna = "net.java.dev.jna:jna-platform:5.12.1"
